# Generated by Django 5.0.14 on 2026-06-01 23:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('preventivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReemplazo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo_cambio', models.TextField()),
                ('fecha_reemplazo', models.DateTimeField(auto_now_add=True)),
                ('equipo_entrante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reemplazos_como_entrante', to='activos.equipo')),
                ('equipo_saliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reemplazos_como_saliente', to='activos.equipo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_cambios', to='activos.seccion')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swaps_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCorrectiva',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_ejecucion', models.CharField(choices=[('INTERNO', 'Personal Interno'), ('TERCERO', 'Proveedor Tercero')], default='INTERNO', max_length=20)),
                ('descripcion_falla', models.TextField()),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True)),
                ('repuestos_utilizados', models.TextField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTO', 'Esperando Repuesto'), ('ESPERANDO_TERCERO', 'Esperando Tercero'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_correctivas', to='activos.equipo')),
                ('informe_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correctivos_derivados', to='preventivo.informemantenimiento')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('tecnico_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tercerizadas', to='correctivo.proveedortercero')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
