# Generated by Django 5.0.14 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencorrectiva',
            name='equipo_inoperativo',
            field=models.BooleanField(default=False),
        ),
    ]
