# Generated by Django 5.0.14 on 2026-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='firma_trazos',
            field=models.JSONField(blank=True, help_text='Coordenadas normalizadas [[[x,y],...],...]', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='firma_digital',
            field=models.ImageField(blank=True, help_text='Imagen generada desde trazos para estampar en PDF', null=True, upload_to='firmas_usuarios/'),
        ),
    ]
