# Generated by Django 5.0.14 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado_operativo',
            field=models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_REPARACION', 'En Reparación'), ('EN_ALMACEN', 'En Almacén'), ('DADO_DE_BAJA', 'Dado de Baja')], default='EN_USO', max_length=20),
        ),
    ]
