# Generated by Django 5.0.14 on 2026-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_vistas_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectivosPendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.UUIDField()),
                ('codigo_orden', models.CharField(max_length=8)),
                ('codigo_activo', models.CharField(max_length=50)),
                ('equipo_nombre', models.CharField(max_length=200)),
                ('descripcion_falla', models.TextField()),
                ('tipo_ejecucion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_resolucion', models.DateTimeField(null=True)),
                ('proveedor_nombre', models.CharField(max_length=150, null=True)),
                ('proveedor_especialidad', models.CharField(max_length=100, null=True)),
                ('tecnico_username', models.CharField(max_length=150, null=True)),
                ('tecnico_nombre', models.CharField(max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('dias_abierto', models.IntegerField(null=True)),
                ('zona_nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'vista_correctivos_pendientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPredictivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.UUIDField()),
                ('codigo_activo', models.CharField(max_length=50)),
                ('equipo_nombre', models.CharField(max_length=200)),
                ('categoria_mantenimiento', models.CharField(max_length=20)),
                ('criticidad', models.CharField(max_length=20)),
                ('programa_id', models.UUIDField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('mes_planificado', models.IntegerField(null=True)),
                ('estado_programa', models.CharField(max_length=20, null=True)),
                ('score_salud_ultimo', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('requiere_tercero', models.BooleanField(null=True)),
                ('informe_id', models.UUIDField(null=True)),
                ('fecha_informe', models.DateField(null=True)),
                ('estado_informe', models.CharField(max_length=20, null=True)),
                ('hallazgos_generales', models.TextField(null=True)),
                ('tecnico_username', models.CharField(max_length=150, null=True)),
                ('tecnico_nombre', models.CharField(max_length=300, null=True)),
                ('zona_nombre', models.CharField(max_length=100, null=True)),
                ('lugar_nombre', models.CharField(max_length=150, null=True)),
                ('seccion_nombre', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'vista_seguimiento_predictivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TasaBajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateTimeField()),
                ('anio', models.FloatField()),
                ('mes_numero', models.FloatField()),
                ('zona_nombre', models.CharField(max_length=100)),
                ('lugar_nombre', models.CharField(max_length=150)),
                ('seccion_nombre', models.CharField(max_length=150)),
                ('equipo_saliente_codigo', models.CharField(max_length=50)),
                ('equipo_saliente_nombre', models.CharField(max_length=200)),
                ('equipo_saliente_marca', models.CharField(max_length=100, null=True)),
                ('equipo_entrante_codigo', models.CharField(max_length=50)),
                ('equipo_entrante_nombre', models.CharField(max_length=200)),
                ('motivo_cambio', models.TextField()),
                ('tecnico_username', models.CharField(max_length=150)),
                ('tecnico_nombre', models.CharField(max_length=300)),
                ('fecha_reemplazo', models.DateTimeField()),
            ],
            options={
                'db_table': 'vista_tasa_bajas',
                'managed': False,
            },
        ),
    ]
