# Generated by Django 5.0.14 on 2026-06-01 22:42

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMantenimiento',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('hallazgos_generales', models.TextField(blank=True, null=True)),
                ('estado_informe', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a Revisión'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_supervisor', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='informes_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='evidencias_mantenimiento/%Y/%m/')),
                ('tipo', models.CharField(choices=[('ANTES', 'Antes'), ('DESPUES', 'Después')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='preventivo.informemantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoDetalleScore',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_valor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observacion_tecnica', models.TextField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_scores', to='activos.mantenimientocomponente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_score', to='preventivo.informemantenimiento')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaMantenimiento',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes_planificado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EJECUTADO', 'Ejecutado'), ('ATRASADO', 'Atrasado')], default='PLANIFICADO', max_length=20)),
                ('score_salud_ultimo', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('requiere_tercero', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='activos.equipo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('equipo', 'anio', 'mes_planificado')},
            },
        ),
        migrations.AddField(
            model_name='informemantenimiento',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='preventivo.programamantenimiento'),
        ),
    ]
