# Generated by Django 5.0.14 on 2026-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemantenimiento',
            name='comentario_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
