# Generated by Django 5.0.14 on 2026-06-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctivo', '0001_initial'),
        ('preventivo', '0002_informemantenimiento_comentario_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programamantenimiento',
            name='proveedor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_asignados', to='correctivo.proveedortercero'),
        ),
        migrations.AlterField(
            model_name='programamantenimiento',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EJECUTADO', 'Ejecutado'), ('ATRASADO', 'Atrasado'), ('PENDIENTE_TERCERO', 'Pendiente de Tercero')], default='PLANIFICADO', max_length=20),
        ),
    ]
