# Generated by Django 5.0.14 on 2026-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0003_programamantenimiento_proveedor_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemantenimiento',
            name='correctivo_auto_generado',
            field=models.BooleanField(default=False),
        ),
    ]
