# Generated by Django 5.0.14 on 2026-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0004_informemantenimiento_correctivo_auto_generado'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemantenimiento',
            name='correctivo_manual_generado',
            field=models.BooleanField(default=False),
        ),
    ]
