# Generated by Django 5.0.14 on 2026-07-03 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctivo', '0001_initial'),
        ('preventivo', '0005_informemantenimiento_correctivo_manual_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informemantenimiento',
            name='correctivo_auto_generado',
        ),
        migrations.RemoveField(
            model_name='informemantenimiento',
            name='correctivo_manual_generado',
        ),
        migrations.RemoveField(
            model_name='programamantenimiento',
            name='proveedor_asignado',
        ),
        migrations.AddField(
            model_name='mantenimientodetallescore',
            name='derivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimientodetallescore',
            name='detalle_intervencion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimientodetallescore',
            name='intervencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimientodetallescore',
            name='orden_derivada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_derivados', to='correctivo.ordencorrectiva'),
        ),
        migrations.AddField(
            model_name='mantenimientodetallescore',
            name='requiere_tercero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimientodetallescore',
            name='score_inicial',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
