# Generated by Django 5.0.14 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0006_remove_informemantenimiento_correctivo_auto_generado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programamantenimiento',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EJECUTADO', 'Ejecutado'), ('ATRASADO', 'Atrasado'), ('PENDIENTE_TERCERO', 'Pendiente de Tercero'), ('STANDBY', 'En Standby')], default='PLANIFICADO', max_length=20),
        ),
    ]
